<?php

/**
 * @file
 * This is a test file to check for codesniffer issues.
 */

/**
 * Implements hook_menu().
 */
function hook_menu() {
  $items['example'] = array(
    'title' => 'Example Page',
    'page callback' => 'example_page',
    'access arguments' => array(
      'access content',
    ),
    'type' => MENU_SUGGESTED_ITEM,
  );
  $items['example/feed'] = array(
    'title' => 'Example RSS feed',
    'page callback' => 'example_feed',
    'access arguments' => array(
      'access content',
    ),
    'type' => MENU_CALLBACK,
  );
  return $items;
}

/**
 * Example page 1 function which returns page.
 *
 * @return string
 *   String of text page.
 */
function example_page() {
  return "page";
}

/**
 * Exampel feed function which returns feed.
 *
 * @return string
 *   Returns the string feed.
 */
function example_feed() {
  return "feed";
}
